gccCompile(darwin, Src, Dep, Obj) :- gccCompileDarwin(Src, Dep, Obj).
gccCompile(linux, Src, Dep, Obj) :-  gccCompileLinux(Src, Dep, Obj).

gccLink(darwin, Objs, Name, Exe) :- gccLinkDarwin(Objs, Name, Exe).
gccLink(linux, Objs, Name, Exe) :- gccLinkLinux(Objs, Name, Exe).

ccCompile(Arch, Src, Dep, Obj) :- gccCompile(Arch, Src, Dep, Obj).
ccLink(Arch, Objs, Name, Exe) :- gccLink(Arch, Objs, Name, Exe).

main(Arch, Src1, H1, Src2, H2, Main, Name, Exe) :- ccCompile(Arch, Src1, [H1], Obj1),
ccCompile(Arch, Src2, [H2], Obj2),
ccCompile(Arch, Main, [H1, H2], ObjMain),
ccLink(Arch, [Obj1, Obj2, ObjMain], Name, Exe).


mainDarwin(Src1, H1, Src2, H2, Main, Exe) :- main(darwin, Src1, H1, Src2, H2, Main, mainDarwin, Exe).
mainLinux(Src1, H1, Src2, H2, Main, Exe) :- main(linux, Src1, H1, Src2, H2, Main, mainLinux, Exe).


mainLinux("repo/src/s1.txt", "repo/src/h1.txt", "repo/src/s2.txt", "repo/src/h2.txt", "repo/src/main.c", EE)?



